### ISSUE TITLE
Undefined method 'subpods'

### ISSUE THREAD

**Issue by ghost** [mkroman/wolfram-alpha#3]
When trying to search for some queries I get the error:  "'<main>': undefined method 'subpods' for nil:NilClass (NoMethorError)".  My code is exactly the same as the code on the home page, with the single exception that the query is from user input, not predefined in the program.  This error does not occur all of the time, and I haven't found any pattern to when it does occur.

**Comment by mkroman** [comment]
That's strange.  So far I haven't experienced any issues.

Could you perhaps change the code to:

``` ruby
input = response["Input"] # Get the input interpretation pod.
result = response.find { |pod| pod.title == "Result" } # Get the result pod.

p response if input.nil? or result.nil?
puts "#{input.subpods[0].plaintext} = #{result.subpods[0].plaintext}"
```

And post the output here, when the error occurs?

**Comment by louismullie** [comment]
Same error on Ruby 2.2.0, everything works on 1.9.3

**Comment by alexishida** [comment]
Same error `block (2 levels) in <main>': undefined method`subpods' for nil:NilClass (NoMethodError)

**Comment by arnoldtonderaimarunda** [comment]
That happens when Wolfram Alpha does not return a result/subpod array for your request. You need to alter your query.
